//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class moviesdb
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime Release_Date { get; set; }
        public string Genre { get; set; }
        public decimal Price { get; set; }
        public string Rating { get; set; }
    }
}
